### ISSUE TITLE
Active repo?

### ISSUE THREAD

**Issue by TheStrangerDoctor** [TindakMalaysia/Penang-Maps#1]
Hello, please specify whether this repository is still maintained. Otherwise, please state it clearly in the README file. Thank you!

**Comment by daneshchacko** [comment]
Hi,

For some Github didn't notify us about the updates. Readme was updated in October 2023 to reflect new corrections and updates

All the Daerah Mengundi, DUN and Parliament boundaries are valid up to GE13
